<Gerenciador>:
    Menu:
        name: 'menu'
    MyImageWidget:
        name: 'MyImageWidget'
    Tarefas:
        name: 'tarefas'

<Menu>:
    BoxLayout:
        orientation:'vertical'
        padding:200
        spacing:50        
        canvas.before:
            Rectangle:
                pos:self.pos
                size:self.size
                source:'cinza.jpg'

        Button:
            text:'Local'
            on_release: app.root.current = 'MyImageWidget'
        Button:
            text:'Objetos'
            on_release: app.root.current = 'tarefas'
        Button:
            text:'Sair'
            on_release:app.stop()
<MyImageWidget>:
    ActionBar:
        ActionView:
            ActionPrevious:
                title:'Menu'
                on_release:app.root.current = 'menu'
            ActionButton:
                text:'Sair'
                on_release:app.stop()


<Tarefas>:
    BoxLayout:
        orientation:'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    title:'Menu'
                    on_release:app.root.current = 'menu'
                ActionButton:
                    text:'Sair'
                    on_release:app.stop()
        ScrollView:
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint_y:None
                height:self.minimum_height
        BoxLayout:
            size_hint_y:None
            height:60
            TextInput:
                id:texto
            Button:
                text:'+'
                size_hint_x:None
                width:60
                on_release:root.addWidget()

<Tarefa>:
    size_hint_y:None
    height:200
    Button:
        id:label
        on_release:app.root.get_screen('tarefas').encontrarObjeto(self.text)
    Button:
        text:'X'
        size_hint_x:None
        width:60
        on_release:app.root.get_screen('tarefas').ids.box.remove_widget(root)
