<Gerenciador>:
    Menu:
        name: 'menu'
    MyImageWidget:
        name: 'MyImageWidget'
    Tarefas:
        name: 'tarefas'
    Root:
        name: 'Root'

<Menu>:
    BoxLayout:
        orientation:'vertical'
        padding:200
        spacing:50
        canvas.before:
            Rectangle:
                pos:self.pos
                size:self.size
                source:'cinza.jpg'
        Button:
            text:'Local'
            on_release: app.root.current = 'MyImageWidget'
        Button:
            text:'Objetos'
            on_release: app.root.current = 'tarefas'
        Button:
            text:'Sair'
            on_release:app.stop()

<MyImageWidget>:
    ActionBar:
        ActionView:
            ActionPrevious:
                title:'Menu'
                on_release:app.root.current = 'menu'
            ActionButton:
                text:'Sair'
                on_release:app.stop()

<Tarefas>:
    BoxLayout:
        orientation:'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    title:'Tarefas'
                    on_release:app.root.current = 'menu'
                ActionButton:
                    text:'Sair'
                    on_release:app.stop()
        ScrollView:
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint_y:None
                height:self.minimum_height
        BoxLayout:
            size_hint_y:None
            height:60
            TextInput:
                id:texto
            Button:
                text:'+'
                size_hint_x:None
                width:60
                on_release:root.addWidget()

<Tarefa>:
    size_hint_y:None
    height:200
    Button:
        id:label
        on_release:app.root.get_screen('tarefas').encontrarObjeto(self.text)
    Button:
        text:'Imagem'
        size_hint_x:None
        width:60
        on_release:app.root.current = 'Root'
        on_release: app.root.get_screen('Root').textoDaTarefa(root)
    Button:
        text:'X'
        size_hint_x:None
        width:60
        on_release:app.root.get_screen('tarefas').removeWidget(root)


<Root>:
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: 'Load'
                on_release: root.show_load()
            Button:
                text: 'Save'
                on_release: root.save()
                on_release: app.root.current = 'tarefas'

        BoxLayout:
            Image:
                id: image
                source: ""
            RstDocument:

                show_errors: True
    ActionBar:
        ActionView:
            ActionPrevious:
                title:'Menu'
                on_release:app.root.current = 'tarefas'
            ActionButton:
                text:'Sair'
                on_release:app.stop()

<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser


        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Load"
                on_release: root.load(filechooser.selection)
